//公共
export const COMMON_LOADING_STATUS = 'COMMON_LOADING_STATUS'
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'
export const UPDATE_LOGIN = 'UPDATE_LOGIN'

//个人信息
export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_BRANCH_INFO = 'GET_BRANCH_INFO'
export const GET_OTHER_INFO = 'GET_OTHER_INFO'

//党建动态
export const GET_NOTICED_NEWS_LIST = 'GET_NOTICED_NEWS_LIST'
export const GET_LEARNED_NEWS_LIST = 'GET_LEARNED_NEWS_LIST'
export const GET_PEOPLED_NEWS_LIST = 'GET_PEOPLED_NEWS_LIST'
export const GET_NEWED_NEWS_LIST = 'GET_NEWED_NEWS_LIST'

//党员动态
export const GET_FINDS_LIST = 'GET_FINDS_LIST'
export const GET_USER_LIST = 'GET_USER_LIST'
export const GET_COMMENT = 'GET_COMMENT'

//公告信息
export const GET_POLICY_NEWS_LIST = 'GET_POLICY_NEWS_LIST'
export const GET_DEEDS_NEWS_LIST = 'GET_DEEDS_NEWS_LIST'
export const GET_GUIDE_NEWS_LIST = 'GET_GUIDE_NEWS_LIST'
export const GET_JOBS_NEWS_LIST = 'GET_JOBS_NEWS_LIST'
export const GET_DEMOCRACY_NEWS_LIST = 'GET_DEMOCRACY_NEWS_LIST'

//我的积分
export const GET_INTEGRAL_LIST = 'GET_INTEGRAL_LIST'
export const GET_INTEGRAL_DETAIL = 'GET_INTEGRAL_DETAIL'

//考试
export const GET_EXAM_LIST = 'GET_EXAM_LIST'

//通讯录
export const GET_PARTY_lIST = 'GET_PARTY_LIST'
export const GET_PERSONAL_LIST = 'GET_PERSONAL_LIST'

